h2 = actxcontrol('LASOMX.LASOMXCtrl.1')
invoke(h2, 'DevOpen', 0, 1)
invoke(h2, 'GetLastError')
% invoke(h2, 'AboutBox')
invoke(h2, 'GetID')
invoke(h2, 'SetOdorValve', 1, 3, 1)
invoke(h2, 'SetOdorValve', 1, 4, 1)
b1 = invoke(h2, 'GetBeam', 1)
b2 = get(h2, 'Active')
release(h2)
