h2 = actxcontrol('LASOMX.LASOMXCtrl.1')
invoke(h2, 'DevOpen', 0, 1)
invoke(h2, 'GetLastError')
% invoke(h2, 'AboutBox')
invoke(h2, 'GetID')
invoke(h2, 'ParseSeqFile', 'FinalValveOn.lsq')
invoke(h2, 'CompileSequence')
invoke(h2, 'LoadAndRunSequencer', 1)
invoke(h2, 'ParseSeqFile', 'FinalValveOff.lsq')
invoke(h2, 'CompileSequence')
invoke(h2, 'LoadAndRunSequencer', 0)
release(h2)
